<html lang="en">
<head>
    <title>Denon controller</title>
    <link rel="stylesheet" href="./node_modules/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="./node_modules/open-iconic/font/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="./receiver.css">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"/>
</head>
<body>
<div class="container-fluid">
    <br/>
    <?php
    include __DIR__ . '/src/templates/zone1.phtml';
    include __DIR__ . '/src/templates/zone2.phtml';
    include __DIR__ . '/src/templates/sources.phtml';
    include __DIR__ . '/src/templates/extra.phtml';
    ?>
</div>
<script src="./node_modules/jquery/dist/jquery.min.js"></script>
<script src="./node_modules/bootstrap/dist/js/bootstrap.js"></script>
<script src="./receiver.js"></script>
</body>
</html>
