<?php

declare(strict_types=1);

use ReceiverControl\Command\Device\Info;

$commands = [
    Info::class => 'Info',
];
?>

<div class="row">
    <div class="col">
        <div class="btn-group d-flex">
            <?php
            foreach ($commands as $command => $label) {
                echo sprintf('<button class="switchable btn btn-outline-secondary text-nowrap" data-command="%s">%s</button>',
                    $command,
                    $label
                );
            }
            ?>
        </div>
    </div>
</div>
